#!/bin/bash

# Function to display usage
usage() {
    echo "Usage: $0 -o <output_dir> -f <fasta_file> [-d <data_dir>] [-g <use_gpu>] [-m <model_name>] [-p <db_preset>] [-t <max_template_date>]"
    exit 1
}

# Default values for optional parameters
data_dir="/projects/alphafold/alphafold_db/afdb/"
use_gpu=FALSE
db_preset="full_dbs"
model_name="monomer"
max_template_date="2022-01-01"

# Parse command line arguments
while getopts ":o:m:f:t:d:g:p:" opt; do
    case $opt in
        o) output_dir="$OPTARG" ;;
        m) model_name="$OPTARG" ;;
        f) fasta_file="$OPTARG" ;;
        t) max_template_date="$OPTARG" ;;
        d) data_dir="$OPTARG" ;;
        g) use_gpu="$OPTARG" ;;
        p) db_preset="$OPTARG" ;;
        *) usage ;;
    esac
done

# Check for required parameters
if [ -z "$output_dir" ] || [ -z "$fasta_file" ]; then
    usage
fi

# Run the command
cat <<EOF > command.txt
apptainer run --env TF_FORCE_UNIFIED_MEMORY=1,XLA_PYTHON_CLIENT_MEM_FRACTION=4.0,OPENMM_CPU_THREADS=8 \
    -B "$data_dir":/db -B ./cache:/etc -B .:/data -B .:/output /projects/alphafold/alphafold_latest.sif \
    --fasta_paths=/data/"$fasta_file" \
    --output_dir=/output/"$output_dir"/ \
    --data_dir=/db/ \
    --db_preset="$db_preset" \
    --bfd_database_path=/db/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
    --uniref90_database_path=/db/uniref90/uniref90.fasta \
    --uniref30_database_path=/db/uniref30/UniRef30_2021_03 \
    --mgnify_database_path=/db/mgnify/mgy_clusters_2022_05.fa \
    --template_mmcif_dir=/db/pdb_mmcif/mmcif_files \
    --max_template_date="$max_template_date" \
    --obsolete_pdbs_path=/db/pdb_mmcif/obsolete.dat \
    --pdb70_database_path=/db/pdb70/pdb70 \
    --model_preset="$model_name" \
    --use_gpu_relax="$use_gpu"
EOF
